### PR TITLE
Cmake split module dirs

### LINKED ISSUE #13: Overriding default cmake find modules?
I am trying to understand why you overriding many default cmake modules. I tried using your repo just for FindLeap but it broke my code using protocol buffers. 

Anyway you split the ones are used for compiling against leap and the custom ones in another directory? 
Or possible include just the FindLeap.cmake and dependencies as part of the release?

### PR DESCRIPTION
**Pull request by benbennett**
Check the documentation changes. I couldn't test it on OSX. Also for some reason the Leap_INCLUDE_DIR doesn't show up in the cached variables, but FindLeap has behaved that way the entire time. Maybe needs mark_as_advance ?

fixes #13 .

### CODE REVIEW

**Comment by codemercenary** [comment]
@wal-rus And this one as well?

**Comment by yeswalrus** [comment]
As useful as this is for external users, as long as we are still the primary consumer of this repo I don't think we should merge these changes since it would make up/downstream merges with our internal code base significantly trickier. It might be worth revisiting this idea a little later though.

**Comment by codemercenary** [comment]
Actually I think it's worth further conversation.  We'd like to see additional use of cmake-modules internally, and this is going to mean avoiding conflict with existing finder packages.  The Autowiring repository, in particular, has been unable to use the cmake-modules repo as is because of the collision @benbennett mentions here; we have had to make substantial modifications to it in order to get it compiling.

Let's leave this PR open and visit it again on Monday.

**Comment by codemercenary** [comment]
I think we can merge this and then make the change upstream in our internal codebase at a later time.  Doing this merge now does mean that we can bring autowiring up-to-date, at least.

**Comment by yeswalrus** [comment]
Fair enough. If we want to commit to doing that change, I think this is pretty good.

**Comment by codemercenary** [comment]
Thanks, @benbennett !  If you've got any other code you want to send our way don't hesistate to send a pull request.

**Pull request merged**
